name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image 1.14.12
      run: docker build 1.14.12 --file Dockerfile --tag ssadok / golang-dev:1.14.12
    - name: Build the Docker image 1.12.6
      run: docker build 1.12.6 --file Dockerfile --tag ssadok / golang-dev:1.12.6
